import type { Metadata } from "next";
import { Check, ExternalLink, Handshake, MapPin, Settings, ShieldCheck, Sparkles, Users } from "lucide-react";
import { CTA, Eyebrow, PageHero } from "@/components/Shared";
import { companyInfo } from "@/data/company";
import { T } from "@/components/Language";
import { pageAlternates } from "@/data/seo";

export const metadata: Metadata = { title: "About Our Elevator Company", description: "Learn about Gentle Elevators, a safety-focused elevator company based in Saida and serving residential and commercial buildings across Lebanon.", alternates: pageAlternates("/about") };
const values = [{ icon: ShieldCheck, name: "Safety", ar: "السلامة" }, { icon: Sparkles, name: "Quality", ar: "الجودة" }, { icon: Check, name: "Reliability", ar: "الموثوقية" }, { icon: Users, name: "Professionalism", ar: "الاحترافية" }, { icon: Handshake, name: "Customer care", ar: "العناية بالعملاء" }, { icon: Settings, name: "Continuous improvement", ar: "التحسين المستمر" }];

export default function About() {
  return <>
    <PageHero title="ABOUT GENTLE ELEVATORS" titleAr="عن GENTLE ELEVATORS" description="Reliable elevator services built around safety, quality, and customer satisfaction." descriptionAr="خدمات مصاعد موثوقة ترتكز على السلامة والجودة ورضا العملاء." />
    <section className="section"><div className="container split"><div className="about-video"><video autoPlay muted loop playsInline preload="metadata" poster="/images/projects/residential-home-elevator/lobby-entrance-wide.jpg" aria-label="Gentle Elevators completed residential elevator showcase"><source src="/videos/residential-home-elevator-showcase.mp4" type="video/mp4" />Your browser does not support embedded video.</video></div><div><Eyebrow><T en="Who we are" ar="من نحن" /></Eyebrow><h2><T en="TECHNICAL CARE. PROFESSIONAL SERVICE." ar="عناية فنية. خدمة احترافية." /></h2><p><T en={<>Gentle Elevators has provided elevator installation, repair, maintenance, modernization, and safety inspection services since {companyInfo.established}. Based in {companyInfo.location}, we support residential and commercial buildings throughout {companyInfo.serviceArea}.</>} ar={<>تقدم Gentle Elevators خدمات تركيب المصاعد وإصلاحها وصيانتها وتحديثها وفحص سلامتها منذ عام {companyInfo.established}. ومن مقرنا في {companyInfo.locationAr} نخدم المباني السكنية والتجارية في {companyInfo.serviceAreaAr}.</>} /></p><div className="company-facts"><div><strong>{companyInfo.established}</strong><span><T en="Established" ar="سنة التأسيس" /></span></div><div><strong><T en="Lebanon" ar="لبنان" /></strong><span><T en="Nationwide service" ar="خدمة في جميع المناطق" /></span></div><div><strong>AR / EN</strong><span><T en="Arabic & English" ar="العربية والإنجليزية" /></span></div></div><div className="mission-grid"><div><h3><T en="Our mission" ar="مهمتنا" /></h3><p><T en="To provide safe, dependable, and high-quality elevator solutions for every customer." ar="تقديم حلول مصاعد آمنة وموثوقة وعالية الجودة لكل عميل." /></p></div><div><h3><T en="Our vision" ar="رؤيتنا" /></h3><p><T en="To become a trusted elevator company known for professional service, strong technical work, and long-term customer relationships." ar="أن نصبح شركة مصاعد موثوقة معروفة بالخدمة الاحترافية والعمل الفني المتقن والعلاقات طويلة الأمد مع العملاء." /></p></div></div></div></div></section>
    <section className="section soft"><div className="container"><div className="center-heading"><Eyebrow><T en="Our values" ar="قيمنا" /></Eyebrow><h2><T en="THE PRINCIPLES BEHIND OUR WORK" ar="المبادئ التي تقود عملنا" /></h2></div><div className="values-grid">{values.map(({ icon: Icon, name, ar }) => <div key={name}><Icon /><h3><T en={name} ar={ar} /></h3></div>)}</div></div></section>
    <section className="section location-section"><div className="container location-grid"><div><Eyebrow><T en="Our location" ar="موقعنا" /></Eyebrow><h2><T en="VISIT GENTLE ELEVATORS" ar="زُر GENTLE ELEVATORS" /></h2><p><T en="Use our verified Google Maps pin for accurate directions to our location." ar="استخدم موقعنا الموثق على خرائط Google للوصول إلينا بدقة." /></p><a className="button button-gold" href={companyInfo.mapUrl} target="_blank" rel="noreferrer"><MapPin /><T en="Open in Google Maps" ar="افتح في خرائط Google" /><ExternalLink /></a></div><div className="map-frame"><iframe src={companyInfo.mapEmbedUrl} title="Gentle Elevators location on Google Maps" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></div></div></section>
    <CTA />
  </>;
}
